version: 2.1
commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
      - image: redislabs/redistimeseries:edge
      
    working_directory: ~/repo

    steps:
      - checkout

      - run: dotnet restore
      - run: dotnet add NRedisTimeSeries.Test package coverlet.collector

      # run tests!

      - run: dotnet test --collect:"XPlat Code Coverage"
      - early_return_for_forked_pull_requests
      - run:
          name: codecov
          command: |
            curl -s https://codecov.io/bash > codecov
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN}
  docs:
    docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1
        - image: circleci/node:10.15
  
    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "76:ad:7c:fa:32:41:29:d0:cc:f6:63:06:62:b6:54:9c"
      - run:
          name: Install and configure dependencies
          command: |
            dotnet add NRedisTimeSeries package Vsxmd
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@redisgraph.io"
            git config user.name "ci-build"
      - run:
          name: Build and create docs
          command: dotnet build
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Updates"  --dist ./docs --branch master --dest ./docs


workflows:
  version: 2
  commit:
    jobs:
      - build
      - docs:
          requires:
            - build
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
